version: "3.9"

services:
  VDRfabric:
    image: fabric_server
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - /home/david.casalod/go/src/github.com/david/fabric-samples:/home/david.casalod/go/src/github.com/david/fabric-samples