version: "3.5"

services:
  vdrfabric:
    image: fabric_server:test2
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${HOST_PORT}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    ports:
      - ${HOST_PORT}:${HOST_PORT}
    volumes:
      - ${SAMPLE_PATH}:${SAMPLE_PATH} 
      - ${CERTPATH}:${CERTPATH}      
      - ${KEYPATH}:${KEYPATH} 
      - ${TLSCERTPATH}:${TLSCERTPATH} 
    networks:
      - uself_net
networks:
  uself_net:
   external: true