version: "3.5"

services:
  vdrfabric:
    image: vdrriv:local 
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${HOST_PORT}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    ports:
      - ${HOST_PORT}:${HOST_PORT}
    volumes:
      - ${SAMPLE_PATH}:${SAMPLE_PATH} 
      - ${CERTPATH}:${CERTPATH}      
      - ${KEYPATH}:${KEYPATH} 
      - ${TLSCERTPATH}:${TLSCERTPATH} 
    networks:
      - uself_net
networks:
  uself_net:
   external: true

#    version: "3.5"

# services:
#   vdrfabric:
#     image:   registry.atosresearch.eu:18487/ari/ledgeruself/fabric-apirest-server:preprod-Supdate
#     environment:
#       - VIRTUAL_HOST=vdrfabric.preprod.ari-bip.eu
#       - VIRTUAL_PORT=3000
#       - LETSENCRYPT_HOST=vdrfabric.preprod.ari-bip.eu

#     volumes:

#       - ${CERTPATH}:${CERTPATH}     
#       - ${KEYPATH}:${KEYPATH} 
#       - ${TLSCERTPATH}:${TLSCERTPATH} 
    
#     networks:
#       - uself_net
# networks:
#   uself_net:
#    external: true