// Code generated by MockGen. DO NOT EDIT.
// Source: fabric/web (interfaces: NetworkInt)

// Package mocks is a generated GoMock package.
package fabric

import (

	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNetworkInt is a mock of NetworkInt interface.
type MockNetworkInt struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkIntMockRecorder
}

// MockNetworkIntMockRecorder is the mock recorder for MockNetworkInt.
type MockNetworkIntMockRecorder struct {
	mock *MockNetworkInt
}

// NewMockNetworkInt creates a new mock instance.
func NewMockNetworkInt(ctrl *gomock.Controller) *MockNetworkInt {
	mock := &MockNetworkInt{ctrl: ctrl}
	mock.recorder = &MockNetworkIntMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkInt) EXPECT() *MockNetworkIntMockRecorder {
	return m.recorder
}

// GetContract mocks base method.
func (m *MockNetworkInt) GetContract(arg0 string) ContractInt {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContract", arg0)
	ret0, _ := ret[0].(ContractInt)
	return ret0
}

// GetContract indicates an expected call of GetContract.
func (mr *MockNetworkIntMockRecorder) GetContract(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContract", reflect.TypeOf((*MockNetworkInt)(nil).GetContract), arg0)
}
